version: 2

before:
  hooks:
    - go mod download

builds:
  - id: logger
    main: ./cmd/packtrack-logger
    binary: packtrack-logger
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: logger-archives
    builds:
      - logger
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - cmd/packtrack-logger/README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  draft: false
  prerelease: auto
  mode: replace
